# GriefPrevention Flags
# Plugin Version: 4.16.1
# Server Version: git-Paper-"40a8c003" (MC: 1.13.2)


World Flags:
  world:
    Default Gamemode: survival
    PvP Only In PvP-Flagged Claims: true
    Message To Send When PvP Is Denied: Player vs. player combat is restricted to
      designated areas.
    Send Message On Enter PvP Enabled Claim: false
    Message: PvP is enabled in this claim, be careful
    Send Message On Exit PvP Enabled Claim: false
    ExitMessage: PvP is disabled in this area, you are now safe
